import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { bodyFont } from "@/components/fonts";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={cn(
					"min-h-screen bg-background font-sans antialiased py-8 px-6",
					bodyFont.className
				)}
			>
				<Header />
				{children}
			</body>
		</html>
	);
}
